In [4]:
import numpy as np
# from transformers import AutoConfig, AutoTokenizer, TFAutoModel
# from keras.utils import plot_model

In [11]:
a = np.load(r'F:\Daneshgah\Arshad\2_4002\NLP\HW5\data\persica.csv_train_x.npy', allow_pickle=True)

In [14]:
a[0]

'وزير علوم  جمع استادان نمونه كشور گفت  استادان نمونه كشور انتظار مي رود كه رويكرد دانايي محوري  گفتمان علمي  عنوان يك بحث فرهنگي  دانشگاهها توسعه  رونق بخشند  گزارش سرويس صنفي آموزشي خبرگزاري دانشجويان ايران  ايسنا  دكتر محمد مهدي زاهدي  اولين مجمع عمومي استادان نمونه دانشگاه هاي سراسر كشور كه  دانشگاه تهران برگزار شد  افزود  توصيه ما  جهت تلاش براي دانايي محوري  توسعه گفتمان علمي  معني عدم تمايل  مباحث سياسي نيست  بلكه برعكس  دانشگاه بايد مهد چالشهاي گفتماني باشد ولي اين امر  بدان معني نيست كه دانشگاه  ابزار دست سياسيون قرار بگيرد  وي تأكيد كرد  دانشگاه نه تنها نبايد تحت تأثير القائات سياسي قرار بگيرد  بلكه بايد خط دهنده  برنامه ريز جريانات سياسي باشد  مهمترين عنصر پياده شدن اين آرمان  دانشجويان  اعضاي هيات علمي دانشگاهها  رأس آنها استادان نمونه هستند  وزير علوم  ذكر اين نكته كه  جامعه اطلاعاتي نمي توان هيچ تفكري  تهديد  ارعاب حاكم كرد  افزود  اگر چه دانشگاهها بايد پرچمدار كرسيهاي آزاد انديشي  حاكميت دانايي محوري باشند  بايد توجه داشته باشند كه ناخودآگاه تحت تأثير جوسازيها  القائات ر

In [8]:
for i in a[1].split():
    print(i)
    

In [3]:
b = np.load(r'F:\Daneshgah\Arshad\2_4002\NLP\HW5\data\persica.csv_train_y.npy')

In [4]:
len(a.tolist())

8911

In [5]:
len(a[0])

1985

In [6]:
len(b)


8911

In [7]:
config = AutoConfig.from_pretrained("HooshvareLab/bert-base-parsbert-uncased", cache_dir=r'F:\Daneshgah\Arshad\2_4002\NLP\HW5\cache')
tokenizer = AutoTokenizer.from_pretrained("HooshvareLab/bert-base-parsbert-uncased", cache_dir=r'F:\Daneshgah\Arshad\2_4002\NLP\HW5\cache')
model = TFAutoModel.from_pretrained("HooshvareLab/bert-base-parsbert-uncased", cache_dir=r'F:\Daneshgah\Arshad\2_4002\NLP\HW5\cache')

Some layers from the model checkpoint at HooshvareLab/bert-base-parsbert-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at HooshvareLab/bert-base-parsbert-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


1000000000000000019884624838653

In [48]:
len(tokenizer.tokenize(text))

37

In [54]:
len(tknz['attention_mask'])

39

In [53]:



text = "ما در هوشواره معتقدیم با انتقال صحیح دانش و آگاهی، همه افراد dfg sgdf sgf sadf  می‌توانند از ابزارهای هوشمند استفاده کنند. شعار ما هوش مصنوعی برای همه است."
tknz = tokenizer(text, max_length=39, truncation=True)
tknz

{'input_ids': [2, 2179, 2028, 3637, 2963, 10517, 2037, 3485, 5371, 2338, 331, 4801, 300, 2440, 2698, 56916, 1196, 70899, 64066, 70899, 1212, 60257, 1212, 3247, 2036, 6559, 3831, 2383, 2362, 15, 4972, 2179, 3637, 8101, 2073, 2440, 2045, 15, 4], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [30]:
type(tknz)

transformers.tokenization_utils_base.BatchEncoding

In [53]:
k = 100
k1 = 25
k2 = 4
a = np.arange(k).reshape((k1, k2))

In [7]:
import numpy as a.n

SyntaxError: invalid syntax (<ipython-input-7-230352956d6d>, line 1)

In [12]:
import transformers


In [9]:
print('Importing pachages...')

import sys
from utils import *
from pathlib import Path
from sklearn.model_selection import train_test_split
from transformers import AutoConfig, AutoTokenizer, TFAutoModel
import keras
import tensorflow as tf
import json


HW_path = Path(r'F:\Daneshgah\Arshad\2_4002\NLP\HW5')

data_folder = HW_path / 'data'
results_folder = HW_path / 'results'

cache_dir = HW_path / 'cache'

config = AutoConfig.from_pretrained("HooshvareLab/bert-base-parsbert-uncased", cache_dir=cache_dir)

Importing pachages...


In [10]:
x_train = np.load(data_folder / 'persica.csv_train_x.npy', allow_pickle=True)[:100].tolist()
y_train = np.load(data_folder / 'persica.csv_train_y.npy')[:100].tolist()


In [11]:
y_train

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1]

In [12]:
train_encodings = tokenizer(x_train, truncation=True, padding=True, max_length=max_length)


NameError: name 'tokenizer' is not defined

In [48]:
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
))


In [49]:
ss = dict(train_encodings)

In [51]:
ss.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [56]:
a = iter(train_dataset)

In [58]:
b = next(a)

In [63]:
b[0]

{'input_ids': <tf.Tensor: shape=(4715,), dtype=int32, numpy=array([   2, 2031, 2248, ...,    0,    0,    0])>,
 'token_type_ids': <tf.Tensor: shape=(4715,), dtype=int32, numpy=array([0, 0, 0, ..., 0, 0, 0])>,
 'attention_mask': <tf.Tensor: shape=(4715,), dtype=int32, numpy=array([1, 1, 1, ..., 0, 0, 0])>}

In [65]:
y_train

['آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'اجتماعي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'آموزشي\n',
 'اجتماعي\n',
 'آموزشي\n',
 'آموزشي\n',
 'اجتماعي\n',
 'آموزشي\n',
 'آموزشي\n',
 'اجتماعي\n',
 'آموزشي\n',
 'اجتماعي\n',
 'اجتماعي\n',
 'اجتماعي\n',
 'اجت

In [64]:
b[1]

<tf.Tensor: shape=(), dtype=string, numpy=b'\xd8\xa2\xd9\x85\xd9\x88\xd8\xb2\xd8\xb4\xd9\x8a\n'>

In [53]:
len(ss['input_ids'])

100

In [54]:
len(ss['input_ids'][0])

4715

In [55]:
max_length

9331

In [13]:
## Data
print('Importing Data...')

x_train = np.load(data_folder / 'persica.csv_train_x.npy', allow_pickle=True).tolist()
y_train = np.load(data_folder / 'persica.csv_train_y.npy').tolist()
x_test = np.load(data_folder / 'persica.csv_test_x.npy', allow_pickle=True).tolist()
y_test = np.load(data_folder / 'persica.csv_test_y.npy').tolist()

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2)

tokenizer = AutoTokenizer.from_pretrained("HooshvareLab/bert-base-parsbert-uncased", cache_dir=cache_dir)
max_length = 9331 #max([len(tokenizer.tokenize(x)) for x in x_train]) + 2

train_encodings = tokenizer(x_train, truncation=True, padding=True, max_length=max_length)
val_encodings = tokenizer(x_val, truncation=True, padding=True, max_length=max_length)
test_encodings = tokenizer(x_test, truncation=True, padding=True, max_length=max_length)

Importing Data...


In [14]:
train_encodings

KeyboardInterrupt: 

In [15]:
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
))


In [54]:
a.shape

(25, 4)

In [55]:
np.sum(a, axis=1, keepdims=True).shape

(25, 1)

In [56]:
u, s, vh = np.linalg.svd(a)

In [57]:
u.shape, s.shape, vh.shape

((25, 25), (4,), (4, 4))

In [58]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [60]:
u[:, :len(s)] @ np.diag(s) @ vh

array([[7.12544698e-17, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [4.00000000e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00],
       [8.00000000e+00, 9.00000000e+00, 1.00000000e+01, 1.10000000e+01],
       [1.20000000e+01, 1.30000000e+01, 1.40000000e+01, 1.50000000e+01],
       [1.60000000e+01, 1.70000000e+01, 1.80000000e+01, 1.90000000e+01],
       [2.00000000e+01, 2.10000000e+01, 2.20000000e+01, 2.30000000e+01],
       [2.40000000e+01, 2.50000000e+01, 2.60000000e+01, 2.70000000e+01],
       [2.80000000e+01, 2.90000000e+01, 3.00000000e+01, 3.10000000e+01],
       [3.20000000e+01, 3.30000000e+01, 3.40000000e+01, 3.50000000e+01],
       [3.60000000e+01, 3.70000000e+01, 3.80000000e+01, 3.90000000e+01],
       [4.00000000e+01, 4.10000000e+01, 4.20000000e+01, 4.30000000e+01],
       [4.40000000e+01, 4.50000000e+01, 4.60000000e+01, 4.70000000e+01],
       [4.80000000e+01, 4.90000000e+01, 5.00000000e+01, 5.10000000e+01],
       [5.20000000e+01, 5.30000000e+01, 5.40000000e

In [1]:
a = [0 for i in range(10)]

In [2]:
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [3]:
a[2] = 1

In [4]:
a


[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

In [7]:
a = dict(r=2,b=3)
c = [i for i in a]

In [8]:
c

['r', 'b']

In [3]:
i = 3
f'sdfkl{i}esdf'

'sdfkl3esdf'

In [1]:
import json

In [7]:
    with open('/Users/parsa/Daneshgah/Arshad/2/NLP/Homeworks/HW4/index_to_label') as fp:
        a = fp.read()

In [8]:
a

'{"0": "\\u0622\\u0645\\u0648\\u0632\\u0634\\u064a\\n", "1": "\\u0627\\u062c\\u062a\\u0645\\u0627\\u0639\\u064a\\n", "2": "\\u062a\\u0627\\u0631\\u064a\\u062e\\u064a\\n", "3": "\\u0627\\u0642\\u062a\\u0635\\u0627\\u062f\\u064a\\n", "4": "\\u0628\\u0647\\u062f\\u0627\\u0634\\u062a\\u064a\\n", "5": "\\u0639\\u0644\\u0645\\u064a\\n", "6": "\\u0633\\u064a\\u0627\\u0633\\u064a\\n", "7": "\\u0641\\u0631\\u0647\\u0646\\u06af\\u064a\\n", "8": "\\u0641\\u0642\\u0647 \\u0648 \\u062d\\u0642\\u0648\\u0642\\n", "9": "\\u0645\\u0630\\u0647\\u0628\\u064a\\n", "10": "\\u0648\\u0631\\u0632\\u0634\\u064a\\n"}'

In [9]:
json.loads(a)

{'0': 'آموزشي\n',
 '1': 'اجتماعي\n',
 '2': 'تاريخي\n',
 '3': 'اقتصادي\n',
 '4': 'بهداشتي\n',
 '5': 'علمي\n',
 '6': 'سياسي\n',
 '7': 'فرهنگي\n',
 '8': 'فقه و حقوق\n',
 '9': 'مذهبي\n',
 '10': 'ورزشي\n'}